// Package relayclient talks to the relay control plane: it creates a session over
// REST and dials the runner WebSocket. It carries no terminal IO and knows nothing
// about the end-to-end keys — the relay is untrusted, so this is deliberately thin.
package relayclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"

	"github.com/coder/websocket"
)

// Client targets one relay origin (e.g. https://relay.example.com).
type Client struct {
	base  *url.URL
	httpc *http.Client
}

// New parses the relay base URL.
func New(base string) (*Client, error) {
	u, err := url.Parse(base)
	if err != nil {
		return nil, fmt.Errorf("relay url: %w", err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return nil, fmt.Errorf("relay url must be http(s), got %q", u.Scheme)
	}
	if u.Host == "" {
		return nil, fmt.Errorf("relay url missing host: %q", base)
	}
	return &Client{base: u, httpc: &http.Client{Timeout: 20 * time.Second}}, nil
}

// Session is the relay's response to a create request. It never contains the
// end-to-end secret — that is generated by the runner and never sent to the relay.
type Session struct {
	ID          string `json:"id"`
	RunnerToken string `json:"runner_token"`
	ExpiresAt   int64  `json:"expires_at"`
}

// CreateSession asks the relay for a new session with the given TTL.
func (c *Client) CreateSession(ctx context.Context, ttl time.Duration) (*Session, error) {
	body, _ := json.Marshal(map[string]int{"ttl_seconds": int(ttl.Seconds())})
	u := c.base.JoinPath("api", "sessions").String()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.httpc.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		snippet, _ := io.ReadAll(io.LimitReader(resp.Body, 256))
		return nil, fmt.Errorf("create session: %s: %s", resp.Status, bytes.TrimSpace(snippet))
	}
	var s Session
	if err := json.NewDecoder(resp.Body).Decode(&s); err != nil {
		return nil, fmt.Errorf("create session: decode: %w", err)
	}
	if s.ID == "" || s.RunnerToken == "" {
		return nil, fmt.Errorf("create session: relay returned an empty id or token")
	}
	return &s, nil
}

// ViewerURL builds the link a browser opens. secretB64 is base64url(S); it goes in
// the fragment, which never reaches the relay. A passphrase is flagged with ".p" so
// the viewer knows to prompt for it.
func (c *Client) ViewerURL(id, secretB64 string, passphrase bool) string {
	u := *c.base
	u.Path = "/s/" + id
	if passphrase {
		secretB64 += ".p"
	}
	u.Fragment = secretB64
	return u.String()
}

// FatalDialError marks a handshake rejection the runner should not retry: the
// session is unknown/expired (404) or the runner token is wrong (401).
type FatalDialError struct {
	Status int
}

func (e *FatalDialError) Error() string {
	switch e.Status {
	case http.StatusUnauthorized:
		return "relay rejected the runner token (401)"
	case http.StatusNotFound:
		return "relay says the session is unknown or expired (404)"
	default:
		return fmt.Sprintf("relay rejected the connection (%d)", e.Status)
	}
}

// DialRunner opens the privileged runner WebSocket. A 401/404 handshake response is
// returned as *FatalDialError; other failures are transient and worth retrying.
func (c *Client) DialRunner(ctx context.Context, id, token string) (*websocket.Conn, error) {
	u := *c.base
	if u.Scheme == "https" {
		u.Scheme = "wss"
	} else {
		u.Scheme = "ws"
	}
	u.Path = "/ws/runner/" + id
	opts := &websocket.DialOptions{
		HTTPHeader: http.Header{"Authorization": {"Bearer " + token}},
	}
	conn, resp, err := websocket.Dial(ctx, u.String(), opts)
	if err != nil {
		if resp != nil && (resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusNotFound) {
			return nil, &FatalDialError{Status: resp.StatusCode}
		}
		return nil, err
	}
	conn.SetReadLimit(2 << 20) // 2 MiB — viewer→runner frames are tiny; this is slack.
	return conn, nil
}
