// Package relayclient talks to the relay control plane: it creates a session over
// REST and dials the runner WebSocket. It carries no terminal IO and knows nothing
// about the end-to-end keys — the relay is untrusted, so this is deliberately thin.
package relayclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"time"

	"github.com/coder/websocket"
)

// Client targets one relay origin (e.g. https://relay.example.com).
type Client struct {
	base  *url.URL
	httpc *http.Client
}

// New parses the relay base URL. Plain http:// is allowed only to a loopback host
// (local development); for any other host it requires https unless allowInsecure
// is set, since the relay delivers executable viewer code and the secret rides in
// a fragment the browser refuses to use over an insecure non-local context.
func New(base string, allowInsecure bool) (*Client, error) {
	u, err := url.Parse(base)
	if err != nil {
		return nil, fmt.Errorf("relay url: %w", err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		// url.Parse reads "localhost:4000" as scheme "localhost", opaque "4000" — the
		// usual scheme-less mistake. Echo the input and suggest the fix.
		if u.Scheme == "" || u.Opaque != "" {
			return nil, fmt.Errorf("relay server %q needs an http(s):// scheme (did you mean http://%s?)", base, base)
		}
		return nil, fmt.Errorf("relay server %q must be http or https, not %q", base, u.Scheme)
	}
	if u.Host == "" {
		return nil, fmt.Errorf("relay server %q is missing a host", base)
	}
	if u.Scheme == "http" && !allowInsecure && !isLoopbackHost(u.Hostname()) {
		return nil, fmt.Errorf("relay server %q is plain http to a non-local host; use https:// (or --allow-insecure for local testing)", base)
	}
	return &Client{base: u, httpc: &http.Client{Timeout: 20 * time.Second}}, nil
}

// isLoopbackHost reports whether host is localhost or a loopback IP literal.
func isLoopbackHost(host string) bool {
	if host == "localhost" {
		return true
	}
	if ip := net.ParseIP(host); ip != nil {
		return ip.IsLoopback()
	}
	return false
}

// Session is the relay's response to a create request. It never contains the
// end-to-end secret — that is generated by the runner and never sent to the relay.
type Session struct {
	ID          string `json:"id"`
	RunnerToken string `json:"runner_token"`
	ExpiresAt   int64  `json:"expires_at"`
}

// CreateSession registers the runner-chosen session id + token with the relay, or
// re-claims them after a node loss. The runner generates both so the SAME session can
// be re-established on any relay node. Returns the relay's view (the assigned expiry).
func (c *Client) CreateSession(ctx context.Context, id, runnerToken string, ttl time.Duration) (*Session, error) {
	body, _ := json.Marshal(map[string]any{
		"id":           id,
		"runner_token": runnerToken,
		"ttl_seconds":  int(ttl.Seconds()),
	})
	u := c.base.JoinPath("api", "sessions").String()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.httpc.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		snippet, _ := io.ReadAll(io.LimitReader(resp.Body, 256))
		return nil, fmt.Errorf("create session: %s: %s", resp.Status, bytes.TrimSpace(snippet))
	}
	var s Session
	if err := json.NewDecoder(resp.Body).Decode(&s); err != nil {
		return nil, fmt.Errorf("create session: decode: %w", err)
	}
	if s.ID == "" || s.RunnerToken == "" {
		return nil, fmt.Errorf("create session: relay returned an empty id or token")
	}
	return &s, nil
}

// ViewerURL builds the link a browser opens. secretB64 is base64url(S); it goes in
// the fragment, which never reaches the relay. A passphrase is flagged with ".p" so
// the viewer knows to prompt for it.
func (c *Client) ViewerURL(id, secretB64 string, passphrase bool) string {
	u := *c.base
	u.Path = "/s/" + id
	if passphrase {
		secretB64 += ".p"
	}
	u.Fragment = secretB64
	return u.String()
}

// FatalDialError marks a handshake rejection the runner should not retry: the
// session is unknown/expired (404) or the runner token is wrong (401).
type FatalDialError struct {
	Status int
}

func (e *FatalDialError) Error() string {
	switch e.Status {
	case http.StatusUnauthorized:
		return "relay rejected the runner token (401)"
	case http.StatusNotFound:
		return "relay says the session is unknown or expired (404)"
	default:
		return fmt.Sprintf("relay rejected the connection (%d)", e.Status)
	}
}

// NotFound reports whether the relay had no such session (404). Unlike a 401 token
// rejection, this is recoverable: the runner can re-create the same id+token (e.g.
// after the relay node was replaced in a deploy) and keep relaying.
func (e *FatalDialError) NotFound() bool { return e.Status == http.StatusNotFound }

// DialRunner opens the privileged runner WebSocket. A 401/404 handshake response is
// returned as *FatalDialError; other failures are transient and worth retrying.
func (c *Client) DialRunner(ctx context.Context, id, token string) (*websocket.Conn, error) {
	u := *c.base
	if u.Scheme == "https" {
		u.Scheme = "wss"
	} else {
		u.Scheme = "ws"
	}
	u.Path = "/ws/runner/" + id
	opts := &websocket.DialOptions{
		HTTPHeader: http.Header{"Authorization": {"Bearer " + token}},
	}
	conn, resp, err := websocket.Dial(ctx, u.String(), opts)
	if err != nil {
		if resp != nil && (resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusNotFound) {
			return nil, &FatalDialError{Status: resp.StatusCode}
		}
		return nil, err
	}
	conn.SetReadLimit(2 << 20) // 2 MiB — viewer→runner frames are tiny; this is slack.
	return conn, nil
}
